title = 'Track Theme'
baseURL = 'https://ghassbomb.github.io/books-track'
languageCode = 'en-us'
description = "Track is the theme for my track sites. I use these sites as repository's of my progress in learning various subjects."
enableRobotsTXT = true

[params]
github = 'https://github.com/ghassbomb/track-theme'